### ISSUE TITLE
Now playing doesn't work

### ISSUE THREAD

**Issue by kahenya** [jurialmunkey/skin.arctic.zephyr#15]
Hi,

I'm still playing catch up with this theme, but so far, I haven't been able to get it to show Now Playing on the videos. Now, my assumption of Now Playing is that when the video starts, an OSD pops up at the bottom for a few seconds and then disappears soon after, kind of like what skin.immersive has. I was actually going to port over what skin.immersive had, once I figured out how to do it, but then when I saw the setting, I put this idea on the side for a minute. 

Is this supposed to work? Are we talking about the same thing?

Sorry to lump things in one post, but just as a pointer, the volume thing on Android is a bummer, where we have to accept that we have two volume bars as of Kodi 15. The Android bar is ugly as sin, and Android guys never felt the need to let people decide if they did not want it or not. Is there a way this can be lowered in position from a skin perspective? I'm thinking z-index, sorry, CSS is more my thing, or even better, give someone the choice of bringing your cooler bar upfront, thus obscuring the Android one and making it seem like one?

Cool skin by the way.

**Comment by jurialmunkey** [comment]
Show now playing video in background does exactly what it says. When in the library, if a video is playing you will see the video in the background instead of the fanart.

There isn't any way to auto show the osd in the skin. Change your keymap settings.

I dont have control over the Android system, only Kodi. 

Also, in the future please post questions and queries on the forum as you will generally get a much quicker response there.
