### ISSUE TITLE
Special episode numbers overlap with other text

### ISSUE THREAD

**Issue by groundpoundfm** [jurialmunkey/skin.arctic.zephyr#32]
In the "Wide" episode view the way the list is formatted causes triple digit episode numbers (S10, E100) to overlap with the episode titles and watched icons like so:

[Imgur link](http://i.imgur.com/AQgTRWt.jpg)

**Comment by jurialmunkey** [comment]
Can you test the latest commit?

https://github.com/jurialmunkey/skin.arctic.zephyr/commit/1923c2655bed8c030ed3e545e0da521af766362c
^^ Theoretically should fix it, but I don't have any specials higher than 9 to test.

**Comment by groundpoundfm** [comment]
Replaced all files and it doesn't change anything, sorry. Still looks the same other than the "disable mouse" message.

**Comment by jurialmunkey** [comment]
I see what the problem is: Because the S is added to Episode number label, it becomes a String instead of an Integer. No way to count number of characters in a String from the skin engine unfortunately, so I'm not really sure of another way to solve this sorry. If I come up with something I will let you know.

**Comment by jurialmunkey** [comment]
Finally figured out a fix for this. Hopefully should be fixed now
