### ISSUE TITLE
Texture Artifacts

### ISSUE THREAD

**Issue by StevenThuriot** [jurialmunkey/skin.arctic.zephyr#6]
With the repo version, I have a severe case of artifacts going on. The github version however didn't show this issue. 

![artifacts](https://cloud.githubusercontent.com/assets/544444/6431723/567965f4-c039-11e4-8fd1-42c83cdb0988.png)

I'm running an HTPC with **Windows 8.1 x64, Kodi 14.1**. I had the same issue with Eminence, but never bothered to look into it as I wasn't running the repo version anyway. 

After some research it turned out that the `Textures.xbt` file was the cause. I've recompiled it a few times, and by setting the `-use_none` flag to `on`, the artifacts are completely gone. The file itself is less than 100kb larger, so it is negligible.

It seems unlikely I'm the only one with this issue. Perhaps it would be wise to recompile the repo's `Textures.xbt` file as well?

**Comment by jurialmunkey** [comment]
I dont actually control this process - the compile is done upstream. I will discuss with some team members and see what can be done.

**Comment by jurialmunkey** [comment]
Actually, I just remmeber that a similar thing happened to some users with Xperience1080. See 
http://forum.kodi.tv/showthread.php?tid=146690&pid=1452707#pid1452707
http://forum.kodi.tv/showthread.php?tid=146690&pid=1453942#pid1453942
Turned out it was a driver issue with that particular video card. 

Using the -use_none flag just means that the textures aren't compressed - so its essentially the same as just having the media folder zipped up in a textures folder, so that isn't really a solution. If you cant find the problem with your drivers, then it might mean simply keeping your own textures.xbt to drop in whenever there is an update, or just using the git version only...

**Comment by StevenThuriot** [comment]
Hi Jurial,

Thanks for the prompt response and going through the trouble of finding the link. I'll roll back a couple of versions tonight and see if that helps. I had seen it before, but IIRC only Intel's APU was affected by this. Since I had this issue on both my AMD as NVidia card, I didn't think about rolling back to check. I'll do that tonight, post the result and just close the issue if that resolves it.

That being said, I don't understand why not using compression isn't a solution. I understand that the Kodi team has been pointing fingers to the graphics cards drivers for ages now concerning the artifacts, but honestly, Kodi is the *only* program that shows issues for me and ever has. This situation basically forces me (and others) to chose between (in case of AMD) graphics drivers with memory leaks or an artifact infested Kodi. And all of that for a 80KB save on a 7.5MB file! :frowning: It's one of those *features* absolutely no one is waiting for. 

Sorry if that sounded rude, but I just felt the need to rant just a little bit. I know this is not your fault nor can you actually do something about it. You're doing an **awesome** job, keep up the good work. The `xbt` file type is just quite infuriating...:pensive: Honestly, we should just be able to [smush](http://www.smushit.com/ysmush.it/) all the images and ship it that way. No one will have issues, deployment is greatly simplified and it will only be a matter of KB's in size difference.

Anyway, thank you for the trouble so far! I'll keep you posted!

**Comment by StevenThuriot** [comment]
I just rolled back up to 10 ATI releases and am still facing the issue. After hitting 2 year old drivers, I decided to call it quits. 

I guess I'm screwed with manual labor from now on. :pensive: Oh well...

Thanks anyway!

**Comment by jurialmunkey** [comment]
Ah strange that you are having that issue on AMD and Nvidia (dont get it on my Radeon 6450 on openelec) - I'm pretty sure the original issue I linked to was limited to Intel chips as you noted...

From what I understand, the reason for textures.xbt compression is largely for performance - file size is not a factor as sometimes an xbt can actually be larger. Basically, I understand that it puts the textures on a canvas sized at power of 2 which loads better into the texture buffer. Further, things like pngs are already compressed so essentially what Kodi has to do is decompress and then convert to the bit format used by the texture buffer -- better performance comes from the textures.xbt being in a bit format that is directly used by the texture buffer rather than converted first. The added DXT compression (what the -use_none flag disables afaik) means that the texture is then smaller, so it loads into the texture buffer faster adding an additional performance boost. 

That's the extent that I understand the technical aspects of it - but I can guarantee that the kodi team has very good reasons for why it is continued to be done that way.

**Comment by StevenThuriot** [comment]
Running a 6850 myself, so that's quite a surprise. I'll tinker with it a bit more eventually and write it down here if I ever end up finding it. It's probably a combination of several (most likely silly) factors.

Thanks for the explanation. It does make sense when you look at it that way. Interesting read! :smile:

**Comment by StevenThuriot** [comment]
In case anyone ever finds this thread, has the same issue and wants to stick with repo builds, I've finally "resolved" the issue by adding the following line to the advanced settings xml:

```xml
<restrictcapsmask>1</restrictcapsmask>
```


More info:

2.11.3 restrictcapsmask
Windows only. A bitmask to prevent XBMC/Kodi from using detected texture capabilities of the GPU.
This helps work around buggy hardware/drivers.

- 1: prevent the use of compressed textures (DXT1, DXT3, DXT5) 
- 2: prevent the use of non-power-of-two dimensions for textures 
- 4: prevent the use of compressed textures with non-power-of-two dimensions.
